pipeline {
  environment {
    registry = "nayazjh/jenkins_work"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  tools { maven "MAVEN_HOME" }
  stages {
    stage('Cloning Git') {
      steps {
            git 'https://github.com/nayazjh/SrpingBoot_BackEnd.git'
      }
    }
    stage('Build') {
       steps {
			dir('restful-web-services') {
				bat 'mvn -Dmaven.test.failure.ignore clean package'
			}
		}
    }
    stage('Test') {
		steps {
			dir('restful-web-services') {
				junit '**/target/surefire-reports/TEST-*.xml'
				archiveArtifacts 'target/*.war'
			}
		}
    }
	stage('SonarQube Analysis') {
		steps {
			dir('restful-web-services') {
				withSonarQubeEnv('sonarqube') {
					bat 'mvn sonar:sonar'
				}
			}
		}
    }
    stage('Building image') {
      steps{
        script {
			dir('restful-web-services') {
				dockerImage = docker.build registry + ":$BUILD_NUMBER"
			}
        }
      }
    }
    stage('Deploy Image') {
      steps{
         script {
			dir('restful-web-services') {
				docker.withRegistry( '', registryCredential ) {
				dockerImage.push()
			  }
			}
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
		  dir('restful-web-services') {
			bat "docker rmi $registry:$BUILD_NUMBER"
		  }
      }
    }
  }

  post {

        success {
            echo 'This Build is Successfull!'
        }
        failure {
            echo 'I failed :('
        }

    }
}